<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import DATA from '../data/stage3_timelines.json'

// Stage 3 (assemble + moduli GEMM) of par_ozaki_async, one rank, one rep, for
// each step of the peer-copy campaign. Generated by
// par_gemmul8/analysis/plots/stage3_export.py from the nsys profiles of jobs
// 2161528-2161531 (all on jpbo-103-23, round 0, rep 0, rank 2). Times are us
// from the start of NVTX range "3 assemble+moduliGEMM".

type Ev = {
  id: string, kind: string, j: number, peer?: number, lane: string, label: string,
  s: number, e: number, launch: number, ready?: number,
}
type Step = { step: string, title: string, job: string, node: string, rank: number, bucket: string, stage_us: number, events: Ev[] }

const STEPS = (DATA as { steps: Step[] }).steps
const RANK = STEPS[0].rank
const PEERS = [0, 1, 2, 3].filter(q => q !== RANK)

const props = defineProps<{ step?: number }>()
const step = ref(props.step ?? 0)
watch(() => props.step, (v) => { if (v !== undefined) step.value = Math.min(v, STEPS.length - 1) })
const cur = computed(() => STEPS[step.value])

// Lanes by what does the work, not by CUDA stream, and the same in every step,
// so a lane that empties out (the copy engines under NCCL, NCCL under peer
// copy) stays on screen.
type Lane = { key: string, name: string, band: 'sm' | 'ce' }
const LANES: Lane[] = [
  { key: 'gemm0', name: 'GEMM 0', band: 'sm' },
  { key: 'gemm1', name: 'GEMM 1', band: 'sm' },
  { key: 'ncclAB', name: 'NCCL A/B', band: 'sm' },
  { key: 'ncclC', name: 'NCCL C', band: 'sm' },
  { key: 'local', name: 'local copies', band: 'sm' },
  ...PEERS.map(q => ({ key: `in${q}`, name: `A/B ← rank ${q}`, band: 'ce' as const })),
  ...PEERS.map(q => ({ key: `out${q}`, name: `C → rank ${q}`, band: 'ce' as const })),
]
const laneIndex = Object.fromEntries(LANES.map((l, i) => [l.key, i]))

function laneOf(ev: Ev): string {
  if (ev.kind === 'gemm') return `gemm${ev.j}`
  if (ev.kind === 'nccl') return ev.lane === 'recv (NCCL)' ? 'ncclAB' : 'ncclC'
  if (ev.kind === 'A' || ev.kind === 'B') return `in${ev.peer}`
  if (ev.kind === 'push') return `out${ev.peer}`
  return 'local' // self, unpack, pack: same-device copies
}

function shortLabel(ev: Ev): string {
  switch (ev.kind) {
    case 'gemm': return `GEMM ${ev.j}`
    case 'nccl': return ev.lane === 'recv (NCCL)' ? `A/B ${ev.j}` : `C ${ev.j}`
    case 'A': case 'B': return `${ev.kind}${ev.j}`
    case 'push': return `C${ev.j}`
    default: return ''
  }
}

const KIND_NAME: Record<string, string> = {
  gemm: 'moduli GEMM (CUTLASS, every SM)',
  nccl: 'NCCL SendRecv kernel (on SMs)',
  A: 'A plane, peer copy (copy engine)',
  B: 'B plane, peer copy (copy engine)',
  push: 'C tile push, peer copy (copy engine)',
  self: 'own plane, same-device copy',
  unpack: 'unpack NCCL receive buffer',
  pack: 'C tile pack, same-device copy',
}

// Every event id across all steps. One that a step doesn't have fades out
// where it last was, rather than vanishing or flying in from 0.
const ALL_IDS = [...new Set(STEPS.flatMap(s => s.events.map(e => e.id)))]
function placed(id: string, at: number): { ev: Ev, here: boolean } {
  const here = STEPS[at].events.find(e => e.id === id)
  if (here) return { ev: here, here: true }
  for (let d = 1; d < STEPS.length; d++) {
    for (const k of [at - d, at + d]) {
      const ev = STEPS[k]?.events.find(e => e.id === id)
      if (ev) return { ev, here: false }
    }
  }
  throw new Error(id)
}

// Time domain: the whole stage, or zoomed on the copy window.
const zoom = ref(false)
const T_MAX = Math.ceil(Math.max(...STEPS.map(s => s.stage_us)) / 500) * 500
const domain = computed(() => zoom.value ? [0, 1600] : [0, T_MAX])
const pct = (t: number) => (t - domain.value[0]) / (domain.value[1] - domain.value[0]) * 100
const ticks = computed(() => {
  const [, d1] = domain.value
  const stepUs = d1 <= 2000 ? 200 : 1000
  return Array.from({ length: Math.floor(d1 / stepUs) + 1 }, (_, i) => i * stepUs)
})
const fmtTick = (t: number) => (t / 1000).toFixed(zoom.value ? 1 : 0)

const bars = computed(() => ALL_IDS.map((id) => {
  const { ev, here } = placed(id, step.value)
  return {
    id, ev, here,
    lane: laneIndex[laneOf(ev)],
    left: pct(ev.s),
    width: pct(ev.e) - pct(ev.s),
    label: shortLabel(ev),
  }
}))

// Hatched spans: work that could have run but hadn't started.
//  - a B copy whose A(j) and B(j-1) had ended, waiting for its link;
//  - the NCCL A/B exchange for GEMM 1, launched early but held until GEMM 0's
//    blocks start retiring and free some SMs.
const waits = computed(() => cur.value.events.flatMap((ev) => {
  let from: number | undefined
  if (ev.kind === 'B' && ev.ready !== undefined && ev.s - ev.ready > 40) from = ev.ready
  if (ev.kind === 'nccl' && ev.lane === 'recv (NCCL)' && ev.s - ev.launch > 200) from = ev.launch
  if (from === undefined) return []
  return [{ id: ev.id, kind: ev.kind, lane: laneIndex[laneOf(ev)], left: pct(from), width: pct(ev.s) - pct(from), us: ev.s - from }]
}))

const gemmStart = (s: Step, j: number) => s.events.find(e => e.kind === 'gemm' && e.j === j)!.s

// One callout per step, numbers taken from the data.
const callout = computed(() => {
  const s = cur.value
  const prev = STEPS[step.value - 1]
  switch (s.step) {
    case 'nccl': {
      const w = waits.value.find(w => w.kind === 'nccl')
      return w && { lane: w.lane, at: w.left, text: `A/B for GEMM 1: launched at ${(cur.value.events.find(e => e.id === w.id)!.launch / 1000).toFixed(1)} ms, can't start until GEMM 0 frees SMs` }
    }
    case 'ab_pull': {
      const w = waits.value.filter(w => w.kind === 'B').sort((a, b) => b.us - a.us)[0]
      return w && { lane: w.lane, at: w.left, text: `B0 ready, but the link is busy with A1 (${Math.round(w.us)} µs)` }
    }
    case 'ab_ordered': {
      const d = gemmStart(prev, 0) - gemmStart(s, 0)
      return { lane: laneIndex.gemm0, at: pct(gemmStart(s, 0)), text: `B0 goes first: GEMM 0 starts ${Math.round(d)} µs earlier` }
    }
    case 'c_push': {
      const p = s.events.filter(e => e.kind === 'push' && e.j === 0).sort((a, b) => a.s - b.s)[0]
      return p && { lane: laneIndex[laneOf(p)], at: pct(p.s), text: 'C tiles leave during GEMM 1, with no NCCL kernel' }
    }
  }
  return null
})

// TOP is the strip above the lanes that holds the callout.
const ROW = 19, GAP = 3, BAND_GAP = 14, TOP = 20
const laneTop = (i: number) => TOP + i * (ROW + GAP) + (LANES[i].band === 'ce' ? BAND_GAP : 0)
const TRACK_H = laneTop(LANES.length - 1) + ROW

const hover = ref<{ ev: Ev, x: number, y: number } | null>(null)
function onEnter(e: MouseEvent, ev: Ev, here: boolean) {
  if (!here) return
  const box = (e.currentTarget as HTMLElement).closest('.track')!.getBoundingClientRect()
  hover.value = { ev, x: e.clientX - box.left, y: e.clientY - box.top }
}

const LEGEND = [
  ['gemm', 'GEMM'], ['nccl', 'NCCL kernel'], ['A', 'A plane'], ['B', 'B plane'],
  ['push', 'C tile'], ['local', 'same-device copy'],
]
</script>

<template>
  <div class="st">
    <div class="head">
      <div class="tabs">
        <button v-for="(s, i) in STEPS" :key="s.step" :class="{ on: i === step }" @click="step = i">
          {{ s.title }}
        </button>
      </div>
      <button class="zoom" :class="{ on: zoom }" @click="zoom = !zoom">
        {{ zoom ? 'whole stage' : 'zoom 0–1.6 ms' }}
      </button>
    </div>

    <div class="body">
      <div class="names" :style="{ height: `${TRACK_H}px` }">
        <div class="band-label sm" :style="{ top: `${laneTop(0)}px`, height: `${laneTop(4) + ROW - laneTop(0)}px` }">SMs</div>
        <div class="band-label ce" :style="{ top: `${laneTop(5)}px`, height: `${laneTop(LANES.length - 1) + ROW - laneTop(5)}px` }">copy engines</div>
        <div v-for="(l, i) in LANES" :key="l.key" class="name" :style="{ top: `${laneTop(i)}px`, height: `${ROW}px` }">{{ l.name }}</div>
      </div>

      <div class="track" :style="{ height: `${TRACK_H}px` }" @mouseleave="hover = null">
        <div v-for="(l, i) in LANES" :key="l.key" class="lane-bg" :class="l.band"
             :style="{ top: `${laneTop(i)}px`, height: `${ROW}px` }" />
        <div v-for="t in ticks" :key="`g${t}`" class="gridline" :style="{ left: `${pct(t)}%` }" />

        <!-- where every other step's stage ended -->
        <div v-for="(s, i) in STEPS" :key="`end${s.step}`" class="end-ghost"
             :class="{ off: i === step }" :style="{ left: `${pct(s.stage_us)}%` }" />

        <div v-for="w in waits" :key="`w${w.id}`" class="wait" :class="`k-${w.kind}`"
             :style="{ top: `${laneTop(w.lane)}px`, height: `${ROW}px`, left: `${w.left}%`, width: `${w.width}%` }" />

        <div v-for="b in bars" :key="b.id" class="bar" :class="[`k-${b.ev.kind}`, { gone: !b.here }]"
             :style="{ top: `${laneTop(b.lane)}px`, height: `${ROW}px`, left: `${b.left}%`, width: `${b.width}%` }"
             @mouseenter="onEnter($event, b.ev, b.here)" @mouseleave="hover = null">
          <span>{{ b.label }}</span>
        </div>

        <div class="end" :style="{ left: `${pct(cur.stage_us)}%`, top: `${TOP}px` }" />

        <template v-if="callout">
          <div class="leader" :style="{ left: `${callout.at}%`, top: '15px', height: `${laneTop(callout.lane) - 15}px` }" />
          <div class="callout" :class="{ flip: callout.at > 55 }" :style="{ left: `${callout.at}%` }">
            {{ callout.text }}
          </div>
        </template>

        <div v-if="hover" class="tip" :class="{ flip: hover.x > 520 }" :style="{ left: `${hover.x}px`, top: `${hover.y + 14}px` }">
          <div class="tip-h">{{ hover.ev.label }}</div>
          <div>{{ KIND_NAME[hover.ev.kind] }}</div>
          <div class="num">{{ (hover.ev.s / 1000).toFixed(3) }}–{{ (hover.ev.e / 1000).toFixed(3) }} ms · {{ Math.round(hover.ev.e - hover.ev.s) }} µs</div>
        </div>
      </div>

      <div />
      <div class="axis">
        <span v-for="t in ticks" :key="`t${t}`" :style="{ left: `${pct(t)}%` }">{{ fmtTick(t) }}</span>
        <b class="end-label" :style="{ left: `${pct(cur.stage_us)}%` }">stage 3 ends {{ (cur.stage_us / 1000).toFixed(2) }} ms</b>
      </div>
    </div>

    <div class="legend">
      <span v-for="[k, name] in LEGEND" :key="k" :class="`k-${k === 'local' ? 'self' : k}`"><i />{{ name }}</span>
      <span class="k-wait"><i />ready, not started</span>
      <em>ms since stage 3 began · rank {{ RANK }}, {{ cur.bucket }} · job {{ cur.job }} on {{ cur.node }}</em>
    </div>
  </div>
</template>

<style scoped>
.st {
  --gemm: #52514e;
  --nccl: #d4a017;
  --A: #2a78d6;
  --B: #eb6834;
  --push: #9a4fd0;
  --local: #1baf7a;
  --ink: #0b0b0b;
  --ink-2: #52514e;
  --ink-3: #8a8984;
  --line: #e4e3df;
  --sm-bg: #f4f3f0;
  --ce-bg: color-mix(in srgb, var(--fzj-lightblue, #adbde3) 18%, white);
  font-size: 12px;
  line-height: 1.3;
  color: var(--ink);
  text-align: left;
}
html.dark .st {
  --gemm: #a3a29c;
  --ink: #ffffff;
  --ink-2: #c3c2b7;
  --line: #3a3a37;
  --sm-bg: #232322;
  --ce-bg: #1e2430;
}

.head { display: flex; align-items: center; gap: 12px; margin-bottom: 8px; }
.tabs { display: flex; gap: 4px; }
.head button {
  border: 1px solid var(--line); border-radius: 4px; padding: 2px 8px;
  font-size: 11.5px; color: var(--ink-2); cursor: pointer; transition: all 0.2s;
}
.head button.on { background: var(--fzj-blue, #023d6b); border-color: var(--fzj-blue, #023d6b); color: white; }
.zoom { margin-left: auto; }

.body { display: grid; grid-template-columns: 112px 1fr; column-gap: 8px; }
.names { position: relative; }
.name {
  position: absolute; right: 0; display: flex; align-items: center;
  font-size: 11px; color: var(--ink-2); white-space: nowrap;
}
.band-label {
  position: absolute; left: 0; writing-mode: vertical-rl; transform: rotate(180deg);
  font-size: 10px; font-weight: 700; letter-spacing: 0.06em; text-transform: uppercase;
  text-align: center; color: var(--ink-3); border-right: 2px solid var(--line); padding-right: 0; width: 14px;
}

.track { position: relative; overflow: hidden; }
.lane-bg { position: absolute; left: 0; right: 0; border-radius: 2px; }
.lane-bg.sm { background: var(--sm-bg); }
.lane-bg.ce { background: var(--ce-bg); }
.gridline { position: absolute; top: 0; bottom: 0; width: 1px; background: var(--line); transition: left 0.6s ease; }

.bar, .wait, .end, .end-ghost, .callout, .leader, .end-label {
  transition: left 0.6s ease, width 0.6s ease, opacity 0.4s ease, top 0.6s ease;
}
.bar {
  position: absolute; background: var(--c); border-radius: 2px;
  box-shadow: inset 0 0 0 0.5px rgb(255 255 255 / 0.6);
  display: flex; align-items: center; justify-content: center; overflow: hidden;
}
.bar span { font-size: 10px; font-weight: 700; color: white; white-space: nowrap; pointer-events: none; }
.bar.gone { opacity: 0; pointer-events: none; }
.wait {
  position: absolute; border-radius: 2px;
  background: repeating-linear-gradient(-45deg, color-mix(in srgb, var(--c) 55%, transparent) 0 2px, transparent 2px 6px);
  box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--c) 60%, transparent);
}

.k-gemm { --c: var(--gemm); }
.k-nccl { --c: var(--nccl); }
.k-A { --c: var(--A); }
.k-B { --c: var(--B); }
.k-push { --c: var(--push); }
.k-self, .k-unpack, .k-pack { --c: var(--local); }
.k-wait { --c: var(--ink-3); }

.end { position: absolute; bottom: 0; width: 0; border-left: 2px solid var(--fzj-red, #eb5f73); }
.end-label {
  position: absolute; top: 15px; transform: translateX(-100%); padding-right: 4px; white-space: nowrap;
  font-size: 11px; color: var(--fzj-red, #eb5f73);
}
.end-ghost { position: absolute; top: 20px; bottom: 0; width: 0; border-left: 1px dashed var(--ink-3); opacity: 0.6; }
.end-ghost.off { opacity: 0; }

.leader { position: absolute; width: 0; border-left: 1.5px solid var(--fzj-red, #eb5f73); z-index: 2; }
.callout {
  position: absolute; top: 0; white-space: nowrap; font-size: 11px; font-weight: 700;
  color: var(--fzj-red, #eb5f73); padding-left: 4px; border-left: 1.5px solid var(--fzj-red, #eb5f73);
  line-height: 15px; z-index: 2;
}
.callout.flip { transform: translateX(-100%); border-left: none; border-right: 1.5px solid var(--fzj-red, #eb5f73); padding-left: 0; padding-right: 4px; }

.axis { position: relative; height: 32px; }
.axis span {
  position: absolute; top: 2px; transform: translateX(-50%); font-size: 10.5px; color: var(--ink-3);
  font-variant-numeric: tabular-nums; transition: left 0.6s ease;
}


.legend { display: flex; flex-wrap: wrap; gap: 4px 14px; margin-top: 2px; font-size: 11px; color: var(--ink-2); }
.legend span { display: inline-flex; align-items: center; gap: 5px; }
.legend em { margin-left: auto; font-style: normal; color: var(--ink-3); }
.legend i { display: inline-block; width: 14px; height: 9px; border-radius: 2px; background: var(--c); }
.legend .k-wait i {
  background: repeating-linear-gradient(-45deg, var(--ink-3) 0 2px, transparent 2px 5px);
  box-shadow: inset 0 0 0 1px var(--ink-3);
}

.tip {
  position: absolute; z-index: 3; transform: translateX(8px); pointer-events: none;
  background: white; border: 1px solid var(--line); border-radius: 6px; box-shadow: 0 2px 8px rgb(0 0 0 / 0.08);
  padding: 5px 8px; white-space: nowrap; color: #0b0b0b;
}
.tip.flip { transform: translateX(calc(-100% - 8px)); }
.tip-h { font-weight: 700; }
.num { font-variant-numeric: tabular-nums; color: #52514e; }
</style>
